### ISSUE TITLE
Warning in Gangstr run

### ISSUE THREAD

**Issue by hchetia** [gymreklab/GangSTR#110]
I am getting the foll. warnings during my Gangstr runs-
[GangSTR-2.5.0] WARNING: Region exceeds maximum total processed reads per sample.
What does this mean ?

best,
hasna

**Comment by zhangjinpengGithub** [comment]
I have the same problem, could you tell me if this warning is serious?

**Comment by nmmsv** [comment]
We have set a maximum number of processed reads per locus since we noticed regions that were "sinks" for reads that had excessive running time (way too many reads mapped to those regions due to something like segmental duplications). However, this threshold is set somewhat arbitrarily for the 30X WGS samples that we were working with at the time. You can increase this threshold if you need to, using this input: `--max-proc-read <int>`

**Comment by zhangjinpengGithub** [comment]
I have the following error, is it serious?
[GangSTR-2.5.0]
SpanClassProb::Divide by Zero prevented!


> We have set a maximum number of processed reads per locus since we noticed regions that were "sinks" for reads that had excessive running time (way too many reads mapped to those regions due to something like segmental duplications). However, this threshold is set somewhat arbitrarily for the 30X WGS samples that we were working with at the time. You can increase this threshold if you need to, using this input: `--max-proc-read <int>`
