### ISSUE TITLE
terminate called after throwing an instance of 'std::out_of_range'

### ISSUE THREAD

**Issue by faithman** [gymreklab/GangSTR#30]
Hi,
Thanks for the nice tool.

When I use GangSTR to run some of my bam files, I keep getting the error:
`terminate called after throwing an instance of 'std::out_of_range'
what():  basic_string::substr: __pos (which is 146) > this->size() (which is 102)
Aborted`
But working well on my rest bam fils. I checked all my bam files and they all in good format. 

 This is the simple command I used.
```GangSTR --bam JU3169.bam --ref WS256.fa --regions whle_for_GangSTR.bed --genomewide --out JU3169```

You can find the bam file with error here:
https://northwestern.box.com/s/sgsizzw7uoynluilswurs098l7nbmdot

Thanks for help!
Ye

**Comment by faithman** [comment]
@nmmsv 
Hi Nima,
I have uploaded files you mentioned. You can find them in the same link.

Thanks,
Ye

**Comment by nmmsv** [comment]
I was able to reproduce the error. The issue is that if the user doesn't input readlength (with --readlength flag), GangSTR tries to find read length from bam file assuming equal read length throughout the bam file. 
problematic.bam contains both 50bps and 150bps reads, and that leads to an estimate for read length that is longer than most of the reads (at 50bps). If you use --readlength 50, I believe you should be able to bypass that error (at least I didn't see an error). However, this may lead to unpredicted results. 

I have to add a more informative error message for this case, so I'll leave the issue open for now. Thanks for reporting this issue!

**Comment by faithman** [comment]
Hi @nmmsv,
Thanks for letting me know. I can go through problematic bam with --readlength flag.
 But, is there a way to work with bam within multiple length reads? I have a merge process to increase coverage for each strain, and this produce those problematic bams. 

Thanks!

**Comment by nmmsv** [comment]
Hi @faithman 
Unfortunately we don't have a plan for supporting variable read lengths at this moment, as this change requires a very significant overhaul of the mathematical model.
