### ISSUE TITLE
Cram Support

### ISSUE THREAD

**Issue by jjfarrell** [gymreklab/GangSTR#35]
Is there any timeline for cram support? I am interested on running this on 5000 crams. 

For a workaround, could the cram reads overlapping the region in the GangSTR reference bed files be extracted and converted to a bam?  An then run GangSTR on the  bam of TRE region reads.   If it works, it would be faster than converting the whole cram to a bam and use much  less space.

**Comment by nmmsv** [comment]
Hello,
Currently we haven't set a timeline for cram support, but I expect that I can work on it in ~2 months.
In the mean time, you can use the workaround method. If you're expecting very large disease associated expansions, make sure to extract the off-target regions (specified in the last column of the bed file) as well.
Since GangSTR tries to find insert size distribution and coverage from the region around the TR, you may get 'Not enough reads to calculate insert size/...' error depending on how high the average coverage of your cram file is. You can either increase size of the region around the repeat to include more reads, or separately calculate those parameters (average and standard deviation of insert size, and average coverage) and feed them to GangSTR.
Please let me know if you still faced errors, and I'll be happy to help. 
Nima

**Comment by bw2** [comment]
.cram support would be really useful for me also

**Comment by nmmsv** [comment]
We just added a release with cram support:
https://github.com/gymreklab/GangSTR/releases/tag/v2.4
Please give it a try and let us know if there is any issue.
