### ISSUE TITLE
how to calculate off-target loci

### ISSUE THREAD

**Issue by bw2** [gymreklab/GangSTR#72]
How can I generate the list of off-target regions for a particular locus?

For HTT, running `bwa mem -a -M` on reads like 
```
@test_read
CAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGC
+
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
```
got me close to the list in 
https://s3.amazonaws.com/gangstr/hg38/HTT_hg38.bed
but still missed a few of the regions.

**Comment by nmmsv** [comment]
Hello,
I believe, since randomness is involved in read generation, it is possible that some runs miss some regions. I don't think that this will make an impact on the outcome of calling.

I have added a script that I previously used that may be helpful. If you increase the `num_reads` parameter, you will usually get more off-target regions.

https://github.com/gymreklab/GangSTR/wiki/Finding-off-target-regions

Please let me know if you had any questions.
Nima

**Comment by bw2** [comment]
Thanks. Trying it out now.  
What value of `num_reads` do you typically use?

**Comment by nmmsv** [comment]
I've used 10000. I think a smaller value should also be ok, but haven't deeply studied the effect of number of reads on the loci that are generated in the script.
