### ISSUE TITLE
Expansions detection

### ISSUE THREAD

**Issue by leorebensabath** [gymreklab/GangSTR#95]
Hi GangSTR team, 

I want to use GangSTR to detect repeat expansions and I have a few questions. 

- Is there a way to output a vcf file with only the STRs with ALT allele different from the reference ? 

- Also I have been trying to use the --str-info flag to be able to identify expansions with DumpSTR. I used a very basic file for a first attempt, this unique line :  

`chr4	3074877	3074933	100`

But when I run GangSTR, I get this warning : 
`WARNING: Unknown STR info column detected... 100`
And in the output vcf file, the 3 values of the QEXP field are -1, even at the location of the str-info file. 
Could you tell me why my formatting of the str-info file is wrong? 

- In the str-info file, what threshold would you advise to use compared to the reference STR length at each location, given that I want to do a global scanning of the genome and not look for one specific pathogenic location ? 

Thanks !

**Comment by nmmsv** [comment]
Hello,
I'll try to answer your questions one by one:

* Currently GangSTR does not produce that kind of output. You need a downstream script/command to make that specific output.
* Does the strinfo file contain a header? The header format is shown here: https://github.com/gymreklab/GangSTR#--str-info
* The threshold highly depends on your application. For example, in a case-control study, you may want to use the maximum allele length of controls as a threshold. If you want to only study expansions that are longer than short read length (to study platform limitations due to short reads or something similar) you can use read length as a threshold.

Please let me know if you have additional questions!
Best,
Nima

**Comment by leorebensabath** [comment]
Thanks a lot this is very helpful ! 
Just another question about the running time, I have a whole genome bam file and GangSTR took about 1h30-2h to process chromosome 1. Is it a regular running time ? Is there any good practice to reduce it ?

**Comment by nmmsv** [comment]
I don't remember the running time on chr1 off the top of my head, but that sounds reasonable to me. For a full whole-genome bam we get ~25h running time on average on a single core. Unfortunately, we haven't yet implemented any parallelization into the method, but you can "manually" parallelize the run if you want. For whole-genome runs, you can use `--chrom` input flag to run each chromosome separately (with a separate GangSTR call), and then merge the results using [mergeSTR](https://github.com/gymreklab/TRTools). To get faster on a single chromosome, you can potentially split the input bed into smaller chunks and run each one separately, and merge. I know, it's not the most elegant solution :D 
Please let me know if you had any other questions!
