### ISSUE TITLE
munmap_chunk(): invalid pointer

### ISSUE THREAD

**Issue by mvcakir** [gymreklab/GangSTR#98]
Hello,

I try to run GangSTR with GRCh38 (version 35) fasta, I use your regions file (hg38_ver13) and it gives this munmap_chunk() error with the first entry already;

ProgressMeter: Processing chr1:10486
munmap_chunk(): invalid pointer
Aborted (core dumped)

The bams are generated by bwa mem mapping with the same reference fa of course.

Below is the call;

GangSTR --bam SRR6761495.bam,SRR6761497.bam,SRR6761499.bam --ref GRCh38.p13.v35.genome.fa --regions hg38_ver13.bed --out GangSTR_test

I have no idea what is wrong here.

Thanks for your help already.

Best Regards

**Comment by nmmsv** [comment]
Hello,
Can you please let me know which version of GangSTR you are currently using? And which operating system you are running on?
Thanks.
Nima

**Comment by mvcakir** [comment]
Dear Nima,

I'm using GangSTR 2.4 on Fedora 32 (workstation ed.).

Volkan

**Comment by nmmsv** [comment]
Hi Volkan,
Can you try using the latest pre-release of GangSTR? We recently fixed a bug that caused core-dump in Ubuntu 20.04 due to a change in compiler optimization.
https://github.com/gymreklab/GangSTR/releases/tag/v2.4.6
We haven't tried running GangSTR on a Fedora system, but our lab uses a CentOS server (which I believe is a derivative of Fedora, correct me if I'm wrong, as I'm not super familiar with Linux distros). So I assume there shouldn't be any major compatibility issues.
Let me know if the latest pre-release didn't work.

**Comment by mvcakir** [comment]
Dear Nima,

Thanks for the quick response and for the help. Last release seems to solve the issue also for the Fedora.

Volkan
